import Head from "next/head";
import { Inter } from "next/font/google";
import MainContainer from "@/components/MainContainer";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useUser } from "@auth0/nextjs-auth0/client";
import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import { useRouter } from "next/router";
import Chat from "@/components/Chat";
import Loading from "@/components/Loading";
import HomeContent from "@/components/HomeContent";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { user, error, isLoading } = useUser();
  const router = useRouter();
  if (isLoading) {
    return <Loading />;
  }
  return (
    <>
      <Head>
        <title>Xzayvian GPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Header isAuthenticated={true} />
        <HomeContent>
          <h1 className="text-2xl lg:text-4xl">Xzayvian GPT</h1>
          <p className="text-lg lg:text-xl capitalize">
            Welcome, {user?.nickname}
          </p>
          <Chat user={user} />
        </HomeContent>
        <Footer />
      </MainContainer>
    </>
  );
}

export const getServerSideProps = withPageAuthRequired();
