import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import MainContainer from "@/components/MainContainer";
import MainContent from "@/components/MainContent";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Button from "@/components/Button";
import Link from "next/link";
import { HiLogin } from "react-icons/hi";
import { useUser } from "@auth0/nextjs-auth0/client";
import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const { user, error, isLoading } = useUser();
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Header/>
        <MainContent>
          <h1 className="text-4xl lg:text-6xl">Xzayvian GPT</h1>
          <p className="text-xl lg:text-2xl">Welcome, {user?.nickname}</p>
          <Link href="/api/auth/logout" className="flex flex-row space-x-2 items-center text-xl lg:text-2xl mt-10 pt-1 pb-1 pl-3 pr-3 w-fit lowercase rounded-full bg-purple-900 bg-opacity-50 text-purple-200 hover:bg-slate-900">
            <span className="text-purple-500">
              <HiLogin />
            </span>
            <p>logout</p>
          </Link>
        </MainContent>
        <Footer/>
      </MainContainer>
    </>
  );
}

export const getServerSideProps = withPageAuthRequired();
