import Head from "next/head";
import { Inter } from "next/font/google";
import MainContainer from "@/components/MainContainer";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useUser } from "@auth0/nextjs-auth0/client";
import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import { useRouter } from "next/router";
import Chat from "@/components/Chat/Chat";
import Loading from "@/components/Loading/Loading";
import HomeContent from "@/components/HomeContent";
import Link from "next/link";
import { HiLogin } from "react-icons/hi";
import Markdown from "markdown-to-jsx";
import { ReactMarkdown } from "react-markdown/lib/react-markdown";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const {user, isLoading, error} = useUser();
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  useEffect(() => {
    if(user)
    {
      setIsAuthenticated(true);
    }
    else
    {
      setIsAuthenticated(false);
    }
  }, [user])

  return (
    <>
      <Head>
        <title>About - Xzayvian GPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Header isAuthenticated={isAuthenticated} />
        <HomeContent>
          <h1 className="text-2xl lg:text-4xl mt-10 lg:mt-0">XZAYVIAN</h1>
          <h1 className="text-2xl lg:text-4xl font-light">GPT</h1>
          <h2 className="text-2xl lg:text-4xl font-light font-mono text-blue-600">v2</h2>
          <p className="text-4xl lg:text-6xl text-blue-600">COMING SOON</p>
        </HomeContent>
        <Footer />
      </MainContainer>
    </>
  );
}
